# Generated by Django 4.2 on 2023-05-01 14:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_cusstomer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cusstomer',
            new_name='Customer',
        ),
    ]
