# Generated by Django 4.2 on 2023-05-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_customer_state_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('TS', 'T_Shirts'), ('JA', 'Jacket'), ('JE', 'Jeans'), ('SW', 'Sweatshirts'), ('TR', 'Trousers'), ('KI', 'Kitwears'), ('AC', 'Accessories')], max_length=2),
        ),
    ]
